#!/bin/bash

mv /usr/local/bin/stew /usr/local/bin/stew-old 2>/dev/null
echo "Downloading latest build..."
curl -s https://stew.sh/steward > /usr/local/bin/stew
chmod +x /usr/local/bin/stew

rm -f /usr/local/bin/stew-old
